config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "recipes#public_recipe_list"
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'

  resources :foods 
  delete 'food/:id', to: 'foods#destroy', as: 'delete_food'

  resources :recipes do
    resources :recipe_foods
  end
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post 'recipes/create', to: 'recipes#create', as: 'create_recipe'
  # get 'recipes/:recipe_id', to: 'recipes#show', as: 'recipe'
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post 'recipes/:recipe_id/toggle_public', to: 'recipes#public_toggle_update', as: 'public_toggle'

end

app/views/menu/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
   <%= link_to "Recipes App", root_path(), :class=> "navbar-brand me-2 text-primary" %>
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <%= link_to "Food", foods_path(), :class=> "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Recipes", recipes_path(), :class=> "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Shopping List", shopping_list_path(), :class=> "nav-link" %>
        </li>
      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
       <% if(user_signed_in?) %>
          <%= button_to "Sign out", destroy_user_session_path, :class => 'btn btn-danger me-3', :method => :delete, data: {turbo: false}%>
        <% end %>
      </div>
    </div>
  </div>
</nav>