config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "recipes#public_recipe_list"
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'

  resources :foods 
  delete 'food/:id', to: 'foods#destroy', as: 'delete_food'

  resources :recipes do
    resources :recipe_foods
  end
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post 'recipes/create', to: 'recipes#create', as: 'create_recipe'
  # get 'recipes/:recipe_id', to: 'recipes#show', as: 'recipe'
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post 'recipes/:recipe_id/toggle_public', to: 'recipes#public_toggle_update', as: 'public_toggle'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :shopping_lists

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true },
                               comparison: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true },
                           comparison: { greater_than_or_equal_to: 0 }
  validates :public, inclusion: { in: [true, false] }, allow_blank: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %i[public show]

  def index
    # @recipes = current_user.recipes.order(created_at: :desc)
    @recipes = Recipe.all.where(user_id: current_user.id).includes(:recipe_foods)
  end

  def new
    @recipe = current_user.recipes.build
    @user = current_user
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfully'
    else
      render :new
    end
  end

  def show
    @recipe_foods = RecipeFood.all.where(recipe_id: params[:id]).includes(:food)
    @shopping_list =
      @recipe = Recipe.find(params[:id])
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe successfully deleted'
    redirect_to recipes_path
  end

  def public_recipe_list
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def public_toggle_update
    @recipe = Recipe.find(params[:recipe_id])
    if @recipe.update_column(:public, public_toggle_params[:public_toggle] == 'true')
      render json: { status: 'successful' }
    else
      render json: { status: 'not successful' }
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end

  def public_toggle_params
    params.permit(:recipe_id, :public_toggle, :authenticity_token)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/index.html.erb
<div class= "container">
<div class="recipe--header">
<h3>Recipes</h3>
<%= link_to 'Add new Recipe', new_recipe_path, class: "btn btn-primary" %>
</div>
<% if @recipes.any? %>
    <table class= "table table-striped">
        <thead>
            <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Preparation Time</th>
            <th>Cooking Time</th>
            </tr>
        </thead>
        <tbody>
            <% @recipes.each do |recipe| %>
            <tr>
                <td>
                <%= link_to recipe.name, recipe_path(recipe) %> 
                <% if can? :delete, recipe %>
                    <%= button_to "Delete", recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
                <% else %>
                    <%= button_to "Delete", recipe_path(recipe), method: :delete, disabled: true, class: "btn btn-danger" %>
                <% end %>
                </td>
                <td><%= recipe.description %></td>
                <td><%= recipe.preparation_time %></td>
                <td><%= recipe.cooking_time %></td>
            </tr>
            <% end %>
        </tbody>
        </table>
    <% else %>
        <p>No recipes created</p>
    <% end %>
</div>

app/views/recipes/new.html.erb
<div class= "container mb-3">
<h3>New Recipe</h3>
<%= bootstrap_form_with model: @recipe do |f| %>
    <h6><%= f.text_field :name %></h6>
    <h6><%= f.text_area :description %></h6>
    <h6><%= f.number_field :preparation_time %></h6>
    <h6><%= f.number_field :cooking_time %></h6>
    <h6><%= f.check_box :public %></h6>
    <%= f.submit 'Create Recipe' %>
<% end %>
</div>

app/views/recipes/public_recipe_list.html.erb
<div class="container">
<h3 class="public--header">Public Recipes</h3>
<div class="public--recipes">
    <% if @recipes.any? %>
        <div class="public-recipe">
            <% @recipes.each do |recipe| %>
                <div class="recipe--name">
                    <h3><%= link_to recipe.name, recipe_path(recipe), class: "recipe" %></h3>
                    By: <%= recipe.user.name %>
                    </div>
                <div class="recipe--description">
                    <p>Preparation time:<%= recipe.preparation_time %></p>
                    <p>Cooking time: <%= recipe.cooking_time %></p>
                </div>
            <% end %>
        </div>
    <% else %>
        <div class="no--recipes">
            <p>No Public recipes added</p>
        </div>
    <% end %>
</div>
</div>

app/views/recipes/show.html.erb
<div>
<h1><%= @recipe.name %></h1>
<% if can? :create, @recipe %>
<label class="switch">
  <input <% if @recipe.public %> <%= :checked %> <% end %> class="slider round" type="checkbox" id="public_toggle" />
  <span class="slider round" onclick="slider()"></span>
</label>
<% end %>
<h4>Preparation time: <%= @recipe.preparation_time %></h4>
<h4>Cooking time: <%= @recipe.cooking_time %></h4>
<h4>Description</h4> <p><%= @recipe.description %></p>
<%= hidden_field_tag :authenticity_token, form_authenticity_token, id: 'csrf-token' %>
</div>
<div class="d-flex justify-content-between pb-4 border-bottom border-dark">
    <%=link_to "Generate shopping list", shopping_list_path(@recipe), data: { turbo_frame: 'modal' }, class: "btn btn-success"%>
    <% if can? :destroy, @recipe %>
        <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), class: "btn btn-primary add-food d-block"%>
    <% end %>
</div>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= link_to recipe_food.food.name, food_path(recipe_food.food)%></td> 
          <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
          <td><%= recipe_food.food.price*recipe_food.quantity %></td>
          <td></td>
           <td class="d-flex">
        <div class="me-3">
            <% if can? :edit, recipe_food.recipe %>
                <%= button_to "Delete", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food), method: :delete, class: "btn btn-danger btn-sm" %>
            <% else %>
                <%= button_to "Delete", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food), method: :delete, class: "btn btn-danger btn-sm", disabled: true%>
            <% end %>
        </div>
         <div>
            <% if can? :delete, recipe_food.recipe %>
                <%= link_to "Edit", edit_recipe_recipe_food_path(recipe_food.recipe_id, recipe_food), method: :edit, class: "btn btn-secondary btn-sm" %>
            <% end %>
        </div>
      </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= javascript_include_tag 'slider' %>