config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "recipes#public_recipe_list"
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'

  resources :foods 
  delete 'food/:id', to: 'foods#destroy', as: 'delete_food'

  resources :recipes do
    resources :recipe_foods
  end
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post 'recipes/create', to: 'recipes#create', as: 'create_recipe'
  # get 'recipes/:recipe_id', to: 'recipes#show', as: 'recipe'
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post 'recipes/:recipe_id/toggle_public', to: 'recipes#public_toggle_update', as: 'public_toggle'

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes

  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :price, :quantity, comparison: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
    respond_to do |format|
      format.html { render :new, locals: { food: @food } }
    end
  end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)
    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    return unless @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully Removed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<div class="d-flex justify-content-end">
  <%= link_to "Add Food", new_food_path(), :class=> "btn btn-primary" %>
</div>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Quantity</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= link_to food.name, food_path(food) %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.price) %></td>
          <td><%= food.quantity %></td>
          <td>
            <%= button_to "Delete", delete_food_path(food), method: :delete, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<h1>Create New Food</h1>
<div>
  <%= form_with(model: @food) do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field(:name, class: "form-control") %>
    </p>
    <p>
      <%= form.label :measurement_unit %><br>
      <%= form.text_field(:measurement_unit, class: "form-control") %>
    </p>
    <p>
      <%= form.label :price %><br>
      <%= form.number_field(:price, :step => "0.01", class: "form-control") %>
    </p>
    <p>
      <%= form.label :quantity %><br>
      <%= form.number_field(:quantity, :step => "0.01", class: "form-control") %>
    </p>
    <p>
      <%= form.submit 'Add Food', :class=> "btn btn-primary" %>
    </p>
  <% end %>
</div>

app/views/foods/show.html.erb
<h1><span class="text-primary"><%= @food.name %></span> details</h1>
<table class="table table-striped table-hover">
    <thead>
      <th>Field</th>
      <th>Details</th>
    </thead>
    <tbody>
      <tr>
        <td>Name: </td>
        <td><%= @food.name %></td>
      </tr><tr>
        <td>Measurement Unit: </td>
        <td><%= @food.measurement_unit %></td>
      </tr>
      <tr>
        <td>Price($)</td>
        <td><%= @food.price %></td>
      </tr>
      <tr>
        <td>Quantity</td>
        <td><%= @food.quantity %></td>
      </tr>
    </tbody>
  </table>