config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "recipes#public_recipe_list"
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'

  resources :foods 
  delete 'food/:id', to: 'foods#destroy', as: 'delete_food'

  resources :recipes do
    resources :recipe_foods
  end
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post 'recipes/create', to: 'recipes#create', as: 'create_recipe'
  # get 'recipes/:recipe_id', to: 'recipes#show', as: 'recipe'
  # delete 'recipe/:recipe_id', to: 'recipes#destroy', as: 'delete_recipe'
  post 'recipes/:recipe_id/toggle_public', to: 'recipes#public_toggle_update', as: 'public_toggle'

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: 'recipe_id'
  belongs_to :food, foreign_key: 'food_id'

  validates :quantity, presence: true, numericality: { only_integer: true },
                       comparison: { greater_than_or_equal_to: 0 }

  def total_value
    quantity * food.price
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def new
    @all_foods = Food.all
    @recipe_food = RecipeFood.new
  end

  def edit
    @all_foods = Food.all
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    recipe_id = params[:recipe_id]
    @recipe_food.recipe_id = recipe_id

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_url(recipe_id), notice: 'Recipe food was successfully created.' }
      else
        format.html do
          rendirect_to new_recipe_recipe_food_url(recipe_id), status: :unprocessable_entity,
                                                              alert: 'Incomplete form submitted'
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_url(@recipe_food.recipe_id), notice: 'Recipe food was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_url, notice: 'Recipe food was successfully destroyed.' }
    end
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= bootstrap_form_with model: recipe_food, url: recipe_recipe_foods_path do |form| %>
  <% if recipe_food.errors.any? %>
    <div class="alert">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :Please_select_a_food_item_to_add, class: "d-block"%>
    <%= form.collection_select :food_id, all_foods, :id, :name, :prompt => true, class: "select-inventory-food" %>
  </div>

  <div>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/edit.html.erb
<div class="container">
  <h3>Edit recipe food:</h3>
  <%= bootstrap_form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe_food.recipe_id, @recipe_food.id), html: {method: "patch"} do |form| %>
    <% if @recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

        <ul>
          <% @recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :Please_select_a_food_item_to_add, class: "d-block mb-2"%>
      <%= form.collection_select :food_id, @all_foods, :id, :name, :prompt => true, class: "select-inventory-food w-75" %>
    </div>

    <div>
      <%= form.number_field :quantity, class: "mt-2" %>
    </div>

    <div class="mt-4">
      <%= form.submit "Update Recipe Food" %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<div class="container mb-3">
<h1>Add ingredient</h1>
 <%= render "form", recipe_food: @recipe_food, all_foods:@all_foods %>
</div>